# Generated by Django 3.1 on 2020-11-16 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Nombre')),
                ('subname', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('mchat_score', models.IntegerField(default=0, verbose_name='Puntuacion Mchat primera etapa')),
                ('mchatrf_score', models.IntegerField(default=0, verbose_name='Puntuacion Mchat segunda etapa')),
                ('positive', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=False, max_length=3, null=True, verbose_name='Positivo')),
                ('positive_tr', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=False, max_length=3, null=True, verbose_name='Positivo confirmado')),
                ('item_score', models.CharField(default='', max_length=21, verbose_name='Lista de respuestas primera etapa')),
                ('item_scoreRF', models.CharField(default='', max_length=128, verbose_name='Lista de respuestas segunda etapa')),
                ('followup_list', models.CharField(default='', max_length=50, verbose_name='Lista de item necesarios a revisar')),
                ('audit_info', models.CharField(default='No aplica', max_length=30, verbose_name='Nivel de audición')),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('U', 'no especificado')], default='', max_length=1, verbose_name='Sexo')),
                ('finish', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=False, max_length=3, null=True, verbose_name='Test Realizado')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=256, verbose_name='Apellidos')),
                ('email', models.EmailField(default='example@mail.com', max_length=256, verbose_name='Email')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='Dirección')),
                ('center', models.CharField(blank=True, default='No especificado', max_length=128, verbose_name='Centro de trabajo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Patient_historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateTimeField(default=django.utils.timezone.now)),
                ('mchat_score', models.IntegerField(default=0, verbose_name='Puntuacion Mchat primera etapa')),
                ('mchatrf_score', models.IntegerField(default=0, verbose_name='Puntuacion Mchat segunda etapa')),
                ('positive', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=False, max_length=3, null=True, verbose_name='Positivo')),
                ('item_score', models.CharField(default='', max_length=21, verbose_name='Lista de respuestas primera etapa')),
                ('item_scoreRF', models.CharField(default='', max_length=128, verbose_name='Lista de respuestas segunda etapa')),
                ('followup_list', models.CharField(default='', max_length=50, verbose_name='Lista de item necesarios a revisar')),
                ('audit_info', models.CharField(default='No aplica', max_length=30, verbose_name='Nivel de audición')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testM.patient')),
            ],
            options={
                'ordering': ['date_test'],
            },
        ),
        migrations.CreateModel(
            name='Mchat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='M-CHAT-R/F', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=1)),
                ('question', models.CharField(default='', max_length=400)),
                ('option', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=None, max_length=3, null=True)),
                ('mchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testM.mchat')),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_item', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('question_group', models.CharField(default='none', max_length=50)),
                ('question', models.CharField(default='', max_length=400)),
                ('option', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=None, max_length=3, null=True)),
                ('extra_option', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testM.item')),
            ],
        ),
    ]
