# Generated by Django 2.2.1 on 2019-10-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='option',
            field=models.BooleanField(choices=[(None, ''), (True, 'Si'), (False, 'No')], default=None, max_length=3, null=True),
        ),
    ]
