# Generated by Django 2.2.1 on 2019-10-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0002_auto_20191004_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='option',
            field=models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=None, max_length=3),
        ),
    ]
