# Generated by Django 3.0.5 on 2020-04-24 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testM', '0004_auto_20191004_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mchat',
            name='id',
        ),
        migrations.AlterField(
            model_name='mchat',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
