# Generated by Django 2.0.13 on 2019-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0004_auto_20190310_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchat',
            name='option',
            field=models.BooleanField(default=True),
        ),
    ]
