# Generated by Django 2.0.13 on 2019-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0005_auto_20190310_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchat',
            name='examples',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='mchat',
            name='puntuacion_mchat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
