# Generated by Django 2.0.13 on 2019-03-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0006_auto_20190310_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchat',
            name='option',
            field=models.BooleanField(default=None),
        ),
    ]
