# Generated by Django 2.0.13 on 2019-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0007_auto_20190313_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchat',
            name='option',
            field=models.BooleanField(choices=[(None, ''), (True, 'Si'), (False, 'No')], default=None, max_length=3),
        ),
    ]
