# Generated by Django 2.2.1 on 2019-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0008_auto_20190313_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchat',
            name='option',
            field=models.NullBooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, max_length=3),
        ),
    ]
