# Generated by Django 3.0.5 on 2020-04-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0008_auto_20200424_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='mchat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testM.Mchat'),
        ),
    ]
