# Generated by Django 3.0.5 on 2020-05-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0011_item_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testM.Item')),
                ('puntuacion_mchat', models.IntegerField(default=0)),
            ],
            bases=('testM.item',),
        ),
        migrations.RemoveField(
            model_name='mchat',
            name='puntuacion_mchat',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
