# Generated by Django 3.0.5 on 2020-05-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0013_patient_puntuacion_mchatrf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='puntuacion_mchatrf',
        ),
        migrations.AddField(
            model_name='item',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
    ]
