# Generated by Django 3.0.5 on 2020-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0014_auto_20200501_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='question_id',
            field=models.IntegerField(default=1),
        ),
    ]
