# Generated by Django 3.0.5 on 2020-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0015_auto_20200503_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
