# Generated by Django 3.0.5 on 2020-05-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0016_auto_20200503_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='puntuacion',
        ),
    ]
