# Generated by Django 3.0.5 on 2020-05-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0017_remove_item_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchat',
            name='name',
            field=models.CharField(default='M-CHAT-R/F', max_length=50),
        ),
    ]
