# Generated by Django 3.0.5 on 2020-05-24 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testM', '0019_patient_puntuacion_mchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
