# Generated by Django 3.0.5 on 2020-06-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0021_auto_20200531_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='positivo',
            field=models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=None, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='FollowUpItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_group', models.CharField(default='none', max_length=50)),
                ('question', models.CharField(default='', max_length=400)),
                ('option', models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=None, max_length=3, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testM.Item')),
            ],
        ),
    ]
