# Generated by Django 3.0.5 on 2020-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0022_auto_20200612_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='puntuacion_mchat',
            new_name='mchat_score',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='positivo',
            new_name='positive',
        ),
        migrations.AddField(
            model_name='patient',
            name='followup_list',
            field=models.CharField(default='00000000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='item_score',
            field=models.CharField(default='00000000000000000000', max_length=21),
        ),
    ]
