# Generated by Django 3.0.5 on 2020-06-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0023_auto_20200615_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupitem',
            name='question_item',
            field=models.CharField(default='', max_length=400),
        ),
    ]
