# Generated by Django 3.0.5 on 2020-07-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0024_followupitem_question_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupitem',
            name='extra_option',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
