# Generated by Django 3.0.5 on 2020-07-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0025_followupitem_extra_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='audit_info',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
