# Generated by Django 3.0.5 on 2020-07-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0026_patient_audit_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['question_id']},
        ),
    ]
