# Generated by Django 3.0.5 on 2020-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0027_auto_20200719_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='item_scoreRF',
            field=models.CharField(default='', max_length=128),
        ),
    ]
