# Generated by Django 3.0.5 on 2020-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0028_patient_item_scorerf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupitem',
            name='question_item',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
