# Generated by Django 3.0.9 on 2020-08-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0031_auto_20200825_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='finish',
            field=models.BooleanField(blank=True, choices=[(None, ''), (True, 'Si'), (False, 'No')], default=False, max_length=3, null=True),
        ),
    ]
