# Generated by Django 3.0.9 on 2020-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0032_patient_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='followup_list',
            field=models.CharField(default='', max_length=50),
        ),
    ]
