# Generated by Django 3.0.9 on 2020-09-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testM', '0033_auto_20200826_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mchatrf_score',
            field=models.IntegerField(default=0),
        ),
    ]
